### PR TITLE
Allow all users to view emergency contact details

### PR DESCRIPTION
**Pull request by boffbowsh**

### CODE REVIEW

**Comment by NeilvB** [comment]
This looks good

**Comment by tijmenb** [comment]
Can you make this user a normal user? Then this would be tested.

https://github.com/alphagov/support/blob/master/spec/features/emergency_contact_details_spec.rb#L9

**Comment by boffbowsh** [comment]
Good shout @tijmenb

**Comment by tijmenb** [comment]
👍

**Pull request merged**
